config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # PUBLIC PAGE ROUTES
  root to: "welcome#index"
  resources :items, only: [:index, :show]
  get '/merchants', to: "merchants#index"

  # NEW USER REGISTRATION ROUTES
  get '/register', to: "users#new"
  resources :users, only: [:create]

  # LOGIN/LOGOUT ROUTES
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  # CART ROUTES
  scope :cart, as: :cart do
    get '/', to: "carts#show"
    delete '/', to: "carts#destroy"
    post '/', to: 'carts#checkout'
    post '/:id', to: 'carts#add_from_show_page',  as: :add_item
    patch '/:id/increment', to: 'carts#increment', as: :increment_item
    patch '/:id/decrement', to: 'carts#decrement', as: :decrement_item
    patch '/:id/remove', to: 'carts#remove_item', as: :remove_item
  end

  # PROFILE ROUTES (AS A USER)
  scope :profile, module: :user, as: :profile do
    get '/', to: "users#show"
    patch '/', to: "users#update"
    get '/edit', to: "users#edit"
    resources :addresses, only: [:new, :create, :destroy, :edit, :update]
  end

  scope :profile, module: :user, as: :user do
    resources :orders, only: [:index, :show]
    patch '/orders/:id/cancel', to: 'orders#cancel', as: :cancel_order
  end

  # DASHBOARD ROUTES (AS A MERCHANT)
  scope :dashboard, module: :merchant, as: :merchant do
    get '/', to: "merchants#show", as: :dashboard
    resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
    patch '/items/:id/disable', to: "items#disable", as: :disable_item
    patch '/items/:id/enable', to: "items#enable", as: :enable_item
    patch '/order_items/:id/fulfill', to: 'order_items#fulfill', as: :fulfill_item
    resources :orders, only: :show
  end

  # ADMIN ROUTES
  namespace :admin do
    get '/dashboard', to: "admins#show"
    patch '/dashboard', to: "admins#ship_order"
    resources :merchants, only: [:index, :show]
    patch '/merchants/:id/disable', to: "merchants#disable", as: :disable_merchant
    patch '/merchants/:id/enable', to: "merchants#enable", as: :enable_merchant
    patch '/merchants/:id/downgrade', to: "merchants#downgrade", as: :downgrade_merchant

    resources :users, only: [:index, :show]
    patch '/users/:id/upgrade', to: "users#upgrade", as: :upgrade_user
  end
end

app/controllers/admin/merchants_controller.rb
class Admin::MerchantsController < Admin::BaseController
  def show
    @merchant = User.find(params[:id])
    @pending_orders = Order.pending_merchant_orders(@merchant)
    if @merchant.user?
      redirect_to admin_user_path(@merchant)
    end 
  end

  def index
    @merchants = User.all_merchants
  end

  def disable
    merchant = User.find(params[:id])
    merchant.update(active: false)
    flash[:notice] = "#{merchant.name}'s account is now disabled."
    redirect_to admin_merchants_path
  end

  def enable
    merchant = User.find(params[:id])
    merchant.update(active: true)
    flash[:notice] = "#{merchant.name}'s account is now enabled.'"
    redirect_to admin_merchants_path
  end

  def downgrade
    merchant = User.find(params[:id])
    merchant.downgrade_to_regular_user
    flash[:success] = "#{merchant.name} has been downgraded to a regular user"
    redirect_to admin_user_path(merchant)
  end
end

app/controllers/merchant/base_controller.rb
class Merchant::BaseController < ApplicationController
  before_action :require_merchant

  private

  def require_merchant
    render file: "/public/404", status: 404 unless current_merchant?
  end
end

app/controllers/merchant/items_controller.rb
class Merchant::ItemsController < Merchant::BaseController
  def index
    @items = current_user.items.where.not(id: nil)
  end

  def new
    @item = current_user.items.new
  end

  def create
    @item = current_user.items.new(item_params)
    if @item.save
      flash[:success] = "#{@item.name} has been added"
      redirect_to merchant_items_path
    else
      flash[:error] = @item.errors.full_messages.join(". ")
      render :new
    end
  end

  def disable
    item = Item.find(params[:id])

    if item.active && item.user.id == current_user.id
      item.update(active: false)
      flash[:success] = "#{item.name} is no longer for sale"
    end

    redirect_to merchant_items_path
  end

  def enable
    item = Item.find(params[:id])

    if !item.active && item.user.id == current_user.id
      item.update(active: true)
      flash[:success] = "#{item.name} is now available for sale"
    end

    redirect_to merchant_items_path
  end

  def destroy
    item = Item.destroy(params[:id])
    flash[:notice] = "You have deleted #{item.name}."
    redirect_to merchant_items_path
  end

  def edit
    @item = Item.find(params[:id])
    if @item.user != current_user
      render file: "/public/404", status: 404
      return
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.user != current_user
      render file: "/public/404", status: 404
      return
    end

    if @item.update(update_params)
      flash[:success] = "#{@item.name} has been updated"
      redirect_to merchant_items_path
    else
      flash[:error] = @item.errors.full_messages.join(". ")
      render :edit
    end
  end

  private

  def item_params
    if params[:item][:image] == ""
      params.require(:item).permit(:name, :description, :price, :inventory)
    else
      params.require(:item).permit(:name, :description, :image, :price, :inventory)
    end
  end

  def update_params
    altered_params = params
    if params[:item][:image] == ""
      altered_params[:item][:image] = nil
    end
    altered_params.require(:item).permit(:name, :description, :image, :price, :inventory)
  end
end

app/controllers/merchant/merchants_controller.rb
class Merchant::MerchantsController < Merchant::BaseController
  def show
    @merchant = current_user
    @merchant_orders = Order.pending_merchant_orders(@merchant)
  end
end

app/controllers/merchant/order_items_controller.rb
class Merchant::OrderItemsController < Merchant::BaseController
  def fulfill
    oi = OrderItem.find(params[:id])
    oi.update(fulfilled: true)
    oi.update_item_inventory
    order = oi.order

    if order.order_items.all?(&:fulfilled)
      order.update(status: 'packaged')
    end

    redirect_to merchant_order_path(order)
    flash[:message] = "Your item was fulfilled."
  end
end

app/controllers/merchant/orders_controller.rb
class Merchant::OrdersController < Merchant::BaseController
  def show
    @merchant = current_user
    @order = Order.find(params[:id])
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  def index
    @active_merchants = User.active_merchants
    @inactive_merchants = User.inactive_merchants
    @top_3_orders_by_quantity = Order.top_3_by_quantity
    @top_3_merchants_by_revenue = User.top_3_by_revenue
    @top_3_merchants_by_quantity = User.top_3_merch_by_quantity
    @fastest_3_merchants = User.fastest_3_merchants
    @slowest_3_merchants = User.slowest_3_merchants
    @top_3_states = User.top_3_states
    @top_3_cities = User.top_3_cities
  end
end

app/views/merchants/index.html.erb
<h1>All Merchants</h1>
<div id="statistics">
  <h2>Statistics</h2>
  <div id="top-3-orders-by-quantity">
    <h3>Orders with Highest Quantity</h3>
    <ol>
      <% @top_3_orders_by_quantity.each do |order| %>
        <li>Order <%= order.id %>: <%= order.total_quantity %></li>
      <% end %>
    </ol>
  </div>
  <div id="top-3-merchants-by-revenue">
    <h3>Merchants with Most Revenue</h3>
    <ol>
      <% @top_3_merchants_by_revenue.each do |merchant| %>
        <li><%= merchant.name %>: <%= number_to_currency(merchant.total_revenue) %></li>
      <% end %>
    </ol>
  </div>
  <div id="top-3-merchants-by-quantity">
    <h3>Merchants with Most Items Sold</h3>
    <ol>
      <% @top_3_merchants_by_quantity.each do |merchant| %>
        <li><%= merchant.name %>: <%= number_to_currency(merchant.total_revenue) %> - <%= merchant.total_quantity %> items sold</li>
      <% end %>
    </ol>
  </div>
  <div id="3-fastest-merchants">
    <h3>Fastest Merchants by Average Fulfillment Time</h3>
    <ol>
      <% @fastest_3_merchants.each do |merchant| %>
        <li><%= merchant.name %>: <%= merchant.avg_time.to_i %> day(s)</li>
      <% end %>
    </ol>
  </div>
  <div id="3-slowest-merchants">
    <h3>Slowest Merchants by Average Fulfillment Time</h3>
    <ol>
      <% @slowest_3_merchants.each do |merchant| %>
        <li><%= merchant.name %>: <%= merchant.avg_time.to_i %> day(s)</li>
      <% end %>
    </ol>
  </div>
  <div id="top-3-states">
    <h3>States with Highest Number of Orders</h3>
    <ol>
      <% @top_3_states.each do |state| %>
        <li><%= state.state %>: <%= state.order_count %> order(s)</li>
      <% end %>
    </ol>
  </div>
  <div id="top-3-cities">
    <h3>Cities with Highest Number of Orders</h3>
    <ol>
      <% @top_3_cities.each do |city| %>
        <li><%= city.city %>, <%= city.state %>: <%= city.order_count %> order(s)</li>
      <% end %>
    </ol>
  </div>
</div>
<% if current_admin? %>
  <h2>Active Merchants</h2>
<% end %>
<% @active_merchants.each do |merchant| %>
  <div id="merchant-id-<%= merchant.id %>" class="card mb-3">
    <div class="row no-gutters col-md-9 card-body">
      <h3 class="card-title">
        <% if current_admin? %>
          <%= link_to merchant.name, admin_merchant_path(merchant) %>
        <% else %>
          <%= merchant.name %>
        <% end %>
      </h3>
      <ul>
        <li>Location: <%= merchant.city %>, <%= merchant.state %>.</li>
        <li>Account Created: <%= Date.strptime(merchant.created_at.to_s) %></li>
      </ul>
      <% if current_admin? %>
        <%= button_to "Disable Merchant", admin_disable_merchant_path(merchant), method: "patch", data: { confirm: 'Are you sure?', disable_with: 'loading...' } %>
      <% end %>
    </div>
  </div>
<% end %>

<% if current_admin? %>
  <h2>Inactive Merchants</h2>
  <% @inactive_merchants.each do |merchant| %>
    <div id="merchant-id-<%= merchant.id %>" class="card mb-3">
      <div class="row no-gutters col-md-9 card-body">
        <h3 class="card-title">
          <% if current_admin? %>
            <%= link_to merchant.name, admin_merchant_path(merchant) %>
          <% else %>
            <%= merchant.name %>
          <% end %>
        </h3>
        <ul>
          <li>Location: <%= merchant.city %>, <%= merchant.state %>.</li>
          <li>Account Created: <%= Date.strptime(merchant.created_at.to_s) %></li>
        </ul>
        <%= button_to "Enable Merchant", admin_enable_merchant_path(merchant), method: "patch", data: { confirm: 'Are you sure?', disable_with: 'loading...' } %>
      </div>
    </div>
  <% end %>
<% end %>