config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # PUBLIC PAGE ROUTES
  root to: "welcome#index"
  resources :items, only: [:index, :show]
  get '/merchants', to: "merchants#index"

  # NEW USER REGISTRATION ROUTES
  get '/register', to: "users#new"
  resources :users, only: [:create]

  # LOGIN/LOGOUT ROUTES
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  # CART ROUTES
  scope :cart, as: :cart do
    get '/', to: "carts#show"
    delete '/', to: "carts#destroy"
    post '/', to: 'carts#checkout'
    post '/:id', to: 'carts#add_from_show_page',  as: :add_item
    patch '/:id/increment', to: 'carts#increment', as: :increment_item
    patch '/:id/decrement', to: 'carts#decrement', as: :decrement_item
    patch '/:id/remove', to: 'carts#remove_item', as: :remove_item
  end

  # PROFILE ROUTES (AS A USER)
  scope :profile, module: :user, as: :profile do
    get '/', to: "users#show"
    patch '/', to: "users#update"
    get '/edit', to: "users#edit"
    resources :addresses, only: [:new, :create, :destroy, :edit, :update]
  end

  scope :profile, module: :user, as: :user do
    resources :orders, only: [:index, :show]
    patch '/orders/:id/cancel', to: 'orders#cancel', as: :cancel_order
  end

  # DASHBOARD ROUTES (AS A MERCHANT)
  scope :dashboard, module: :merchant, as: :merchant do
    get '/', to: "merchants#show", as: :dashboard
    resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
    patch '/items/:id/disable', to: "items#disable", as: :disable_item
    patch '/items/:id/enable', to: "items#enable", as: :enable_item
    patch '/order_items/:id/fulfill', to: 'order_items#fulfill', as: :fulfill_item
    resources :orders, only: :show
  end

  # ADMIN ROUTES
  namespace :admin do
    get '/dashboard', to: "admins#show"
    patch '/dashboard', to: "admins#ship_order"
    resources :merchants, only: [:index, :show]
    patch '/merchants/:id/disable', to: "merchants#disable", as: :disable_merchant
    patch '/merchants/:id/enable', to: "merchants#enable", as: :enable_merchant
    patch '/merchants/:id/downgrade', to: "merchants#downgrade", as: :downgrade_merchant

    resources :users, only: [:index, :show]
    patch '/users/:id/upgrade', to: "users#upgrade", as: :upgrade_user
  end
end

app/views/admin/admins/show.html.erb
<h1>Dashboard</h1>
<h3>Packaged Orders:</h3>
<% if @packaged_orders.none? %>
  <h3>There are no packaged orders ready to ship.</h3>
<% else %>
  <div class="orders-index" id="packaged-orders">
    <% @packaged_orders.each do |order| %>
    <section id="order-id-<%= order.id %>" class="card mb-3">
      <div class="row no-gutters col-md-9 card-body">
        <%= link_to order.user.name, admin_user_path(order.user), class: "card-title" %>
        <ul>
          <li>Order Id: <%= order.id %></li>
          <li>Order Status: <%= order.status %></li>
          <li>Created At: <%= Date.strptime(order.created_at.to_s) %></li>
          <li><%= button_to "Ship", admin_dashboard_path(order), method: :patch %></li>
        </ul>

      </div>
    </section>
    <% end %>
  </div>
<% end %>
<% if @pending_orders.any? %>
  <h3>Pending Orders:</h3>
  <div class="orders-index" id="pending-orders">
    <% @pending_orders.each do |order| %>
    <section id="order-id-<%= order.id %>" class="card mb-3">
      <div class="row no-gutters col-md-9 card-body">
        <%= link_to order.user.name, admin_user_path(order.user), class: "card-title" %>
        <ul>
          <li>Order Id: <%= order.id %></li>
          <li>Order Status: <%= order.status %></li>
          <li>Created At: <%= Date.strptime(order.created_at.to_s) %></li>
        </ul>
      </div>
    </section>
    <% end %>
  </div>
<% end %>
<% if @shipped_orders.any? %>
  <h3>Shipped Orders:</h3>
  <div class="orders-index" id="shipped-orders">
    <% @shipped_orders.each do |order| %>
    <section id="order-id-<%= order.id %>" class="card mb-3">
      <div class="row no-gutters col-md-9 card-body">
        <%= link_to order.user.name, admin_user_path(order.user), class: "card-title" %>
        <ul>
          <li>Order Id: <%= order.id %></li>
          <li>Order Status: <%= order.status %></li>
          <li>Created At: <%= Date.strptime(order.created_at.to_s) %></li>
        </ul>
      </div>
    </section>
    <% end %>
  </div>
<% end %>
<% if @cancelled_orders.any? %>
  <h3>Cancelled Orders:</h3>
  <div class="orders-index" id="cancelled-orders">
    <% @cancelled_orders.each do |order| %>
    <section id="order-id-<%= order.id %>" class="card mb-3">
      <div class="row no-gutters col-md-9 card-body">
        <%= link_to order.user.name, admin_user_path(order.user), class: "card-title" %>
        <ul>
          <li>Order Id: <%= order.id %></li>
          <li>Order Status: <%= order.status %></li>
          <li>Created At: <%= Date.strptime(order.created_at.to_s) %></li>
        </ul>
      </div>
    </section>
    <% end %>
  </div>
<% end %>