config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # PUBLIC PAGE ROUTES
  root to: "welcome#index"
  resources :items, only: [:index, :show]
  get '/merchants', to: "merchants#index"

  # NEW USER REGISTRATION ROUTES
  get '/register', to: "users#new"
  resources :users, only: [:create]

  # LOGIN/LOGOUT ROUTES
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  # CART ROUTES
  scope :cart, as: :cart do
    get '/', to: "carts#show"
    delete '/', to: "carts#destroy"
    post '/', to: 'carts#checkout'
    post '/:id', to: 'carts#add_from_show_page',  as: :add_item
    patch '/:id/increment', to: 'carts#increment', as: :increment_item
    patch '/:id/decrement', to: 'carts#decrement', as: :decrement_item
    patch '/:id/remove', to: 'carts#remove_item', as: :remove_item
  end

  # PROFILE ROUTES (AS A USER)
  scope :profile, module: :user, as: :profile do
    get '/', to: "users#show"
    patch '/', to: "users#update"
    get '/edit', to: "users#edit"
    resources :addresses, only: [:new, :create, :destroy, :edit, :update]
  end

  scope :profile, module: :user, as: :user do
    resources :orders, only: [:index, :show]
    patch '/orders/:id/cancel', to: 'orders#cancel', as: :cancel_order
  end

  # DASHBOARD ROUTES (AS A MERCHANT)
  scope :dashboard, module: :merchant, as: :merchant do
    get '/', to: "merchants#show", as: :dashboard
    resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
    patch '/items/:id/disable', to: "items#disable", as: :disable_item
    patch '/items/:id/enable', to: "items#enable", as: :enable_item
    patch '/order_items/:id/fulfill', to: 'order_items#fulfill', as: :fulfill_item
    resources :orders, only: :show
  end

  # ADMIN ROUTES
  namespace :admin do
    get '/dashboard', to: "admins#show"
    patch '/dashboard', to: "admins#ship_order"
    resources :merchants, only: [:index, :show]
    patch '/merchants/:id/disable', to: "merchants#disable", as: :disable_merchant
    patch '/merchants/:id/enable', to: "merchants#enable", as: :enable_merchant
    patch '/merchants/:id/downgrade', to: "merchants#downgrade", as: :downgrade_merchant

    resources :users, only: [:index, :show]
    patch '/users/:id/upgrade', to: "users#upgrade", as: :upgrade_user
  end
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(cart_session_hash)
    @contents = cart_session_hash || Hash.new(0)
  end

  def add_item(item_id)
    @contents[item_id.to_s] = count_of(item_id.to_s) + 1
  end

  def total_count
    @contents.values.sum
  end

  def count_of(item_id)
    @contents[item_id.to_s].to_i
  end

  def item_and_quantity_hash
    @contents.map do |item_id, quantity|
      [Item.find(item_id.to_i), quantity]
    end.to_h
  end

  def subtotal(item)
    quantity = item_and_quantity_hash[item]
    item.price * quantity
  end

  def grand_total
    item_and_quantity_hash.sum do |item, quantity|
      item.price * quantity
    end
  end

  def is_not_empty
    @contents.keys.any?
  end

  def remove_item(item_id)
    @contents[item_id.to_s] = count_of(item_id.to_s) - 1
    if @contents[item_id.to_s] <= 0
      @contents.delete(item_id.to_s)
    end
  end

  def remove_all_item(item_id)
    @contents.delete(item_id.to_s)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper

  def add_from_show_page
    item = Item.find(params[:id])
    add_to_cart(item)
    session[:cart] = cart.contents
    redirect_to items_path
  end

  def increment
    item = Item.find(params[:id])
    add_to_cart(item)
    session[:cart] = cart.contents
    flash[:notice] = "You have added 1 #{item.name} to your cart."
    redirect_back fallback_location: cart_path
  end

  def decrement
    item = Item.find(params[:id])
    cart.remove_item(item.id)
    flash[:notice] = "You now removed 1 #{item.name} in your cart."
    session[:cart] = cart.contents
    redirect_back fallback_location: cart_path
  end

  def remove_item
    item = Item.find(params[:id])
    cart.remove_all_item(item.id)
    flash[:notice] = "You now removed all #{item.name} in your cart."
    session[:cart] = cart.contents
    redirect_back fallback_location: cart_path
  end

  def show
    if current_user && (current_user.admin? || current_user.merchant?)
      render file: "/public/404", status: 404
    end
  end

  def destroy
    session.delete(:cart)
    flash[:message] = "Your cart is now empty, anti-capitalist!"
    redirect_to cart_path
  end

  def checkout
    address = Address.find(params[:address_id])
    # new_order = current_user.orders.create
    new_order = Order.create
    new_order.address_id = address.id
    current_user.orders << new_order
    new_order.save
    cart.item_and_quantity_hash.each do |item, quantity|
      OrderItem.create(item: item, order: new_order, quantity: quantity, price_per_item: item.price)
    end
    session.delete(:cart)
    flash[:message] = "Your order was created!"
    redirect_to user_orders_path
  end

  private

  def add_to_cart(item)
    if cart.count_of(item.id) + 1 <= item.inventory
      cart.add_item(item.id)
      quantity = cart.count_of(item.id)
      flash[:notice] = "You now have #{pluralize(quantity, item.name)} in your cart."
    else
      flash[:error] = "Merchant does not have any more #{item.name}"
    end
  end
end

app/views/carts/show.html.erb
<% if cart.is_not_empty %>
  <% cart.item_and_quantity_hash.each do |item, quantity| %>
    <div id="item-<%= item.id %>" class="card mb-3>
      <div class="row no-gutters">
        <%= image_tag item.image || @default_image, alt: "image of #{item.name}", class: "col-md-3 card-img" %>
        <div class="col-md-9">
          <div class="card-body">
            <h5 class="card-title"><%= link_to item.name, item_path(item) %></h5>
            <p class="card-text"><%= item.user.name %></p>
            <p class="card-text"><%= number_to_currency(item.price) %></p>
            <div class="quantities" >
              Quantity:<%= button_to "-", cart_decrement_item_path(item), method: :patch%><%= quantity %>
              <%= button_to "+", cart_increment_item_path(item), method: :patch %>
              <%= button_to "Remove", cart_remove_item_path(item), method: :patch%>
            </div>
            <p class="card-text">Subtotal: <%= number_to_currency(cart.subtotal(item)) %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <h2>Grand Total: <%= number_to_currency(cart.grand_total) %></h2>

  <% if current_user?  %>
    <% current_user.addresses.each do |address| %>
      <%= button_to "Check Out: Ship to #{address.street}, #{address.city}, #{address.state}", cart_path(address_id: address) %>
      <% end %>
  <% end %>
  <%= button_to "Empty Cart", { controller: :carts, action: :destroy }, method: :delete %>
<% else %>
  <h1>There is nothing in your cart!</h1>
<% end %>

<% if !current_user?  %>
  <div id="visitor-checkout">
    <h1>You must <%= link_to "register", register_path %> or <%= link_to "log in", login_path %> to finish the checkout process.</h1>
  </div>
<% end %>